In [3]:
import pandas as pd

In [4]:
import pandas as pd

# Load existing CSV
df = pd.read_csv(
    "/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/weizmann.csv",
    dtype={"ID": str}
)

In [5]:

# Split Sequence column (format: VL_VH)
vl_vh = df["Sequence"].str.split("_", expand=True)

# Create new dataframe
df_new = pd.DataFrame({
    "pdb_name": df["ID"],
    "VH_seq": vl_vh[1],
    "VL_seq": vl_vh[0],
})

df_new['Resolution'] = 3.5
df_new['split'] = 'train'
df_new['pdb_name'] = df_new['pdb_name'] + '_pdb'
# Save to new CSV
#df_new.to_csv("/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/reformatted_weizmann.csv", index=False)

df_new.head()

,pdb_name,VH_seq,VL_seq,Resolution,split
0,010101010101010101_pdb,QVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLE...,DIELTQSPATLSVTPGDSVSLSCRASQSISNNLHWYQQKSHESPRL...,3.5,train
1,020101010101010101_pdb,QVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLE...,DIELTQSPATLSVTPGDSVSLSCRASQSINNNLHWYQQKSHESPRL...,3.5,train
2,030101010101010101_pdb,QVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLE...,DIELTQSPATLSVTPGDSVSLSCRASQSIGNNLHWYQQKSHESPRL...,3.5,train
3,010201010101010101_pdb,QVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLE...,DIELTQSPATLSVTPGDSVSLSCRASQSISNNLHWYQQKSHESPRL...,3.5,train
4,020201010101010101_pdb,QVQLQESGAEVMKPGASVKISCKATGYTFSTYWIEWVKQRPGHGLE...,DIELTQSPATLSVTPGDSVSLSCRASQSINNNLHWYQQKSHESPRL...,3.5,train

In [6]:
df_new.describe()

       Resolution
count      6912.0
mean          3.5
std           0.0
min           3.5
25%           3.5
50%           3.5
75%           3.5
max           3.5

In [7]:
import pandas as pd
df = pd.read_csv("/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/reformatted_weizmann.csv")          # same file used by your DataModule
mask = ~df['pdb_name'].apply(lambda x: isinstance(x, str) and x != '')
print("Non-string or empty pdb_name rows (first 20):")
print(df.loc[mask, ['pdb_name']].head(20))
print("Counts by type:")
print(df['pdb_name'].apply(type).value_counts())

Non-string or empty pdb_name rows (first 20):
Empty DataFrame
Columns: [pdb_name]
Index: []
Counts by type:
pdb_name
<class 'str'>    6912
Name: count, dtype: int64

In [ ]:
weizmann_df = pd.read_csv("/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/weizmann.csv", dtype={"ID": str})
weizmann_df['ID'] = weizmann_df['ID'] + '_pdb'
WT_ID = '010101010101010101_pdb'
rmsd = pd.read_csv('/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/cdr_rmsds.csv')
rmsf = pd.read_csv('/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/cdr_rmsfs.csv')
rmsd_merged = pd.merge(weizmann_df, rmsd, on='ID', how='left')
rmsf_merged = pd.merge(weizmann_df, rmsf, on='ID', how='left')

rmsd_merged.to_csv('/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/weizmann_with_rmsd.csv', index=False)
rmsf_merged.to_csv('/ceph/opig-shared/users/haque/DPhil/ABB4/ABB4/weizmann_with_rmsf.csv', index=False)